---
title: "Create DB"
author: "Witold Wolski"
date: "30 September 2015"
output: pdf_document
---


```{r}
library(pepfdr)
library(seqinr)

```

# create db

```{r}
rm(list=ls())
file = file.path(path.package("pepfdr"),"extdata/fgcz_contaminants_20150123.fasta")

contaminants <- read.fasta(file, as.string = TRUE, seqtype="AA")
length(contaminants)
msqc1 <- read.fasta("../data/fastaFiles/msqc1-sequences.fasta", as.string = TRUE, seqtype="AA")

toremove <- NULL

for(i in 1:length(msqc1)){
  idx <- grep(msqc1[[i]],contaminants)
  toremove<-c(toremove,idx)
  print(idx)
}

contNoMSQC1 <- contaminants[-toremove]
length(contNoMSQC1)

contaminantsrev <- reverseSeq(contNoMSQC1)
msqc1rev <- reverseSeq(msqc1)


ecoli <- read.fasta("../data/fastaFiles/uniprot-taxonomy83333.fasta",as.string=TRUE, seqtype="AA")
human <- read.fasta("../data/fastaFiles/uniprot-taxonomyHomoSapiensHuman9606.fasta",as.string=TRUE, seqtype="AA")

length(ecoli)
length(human)
ecoliRev <- reverseSeq(ecoli)
humanRev <- reverseSeq(human)

# add human ...
# ecoli .... 

all_d <-c(msqc1, ecoli, human, contNoMSQC1,  msqc1rev, ecoliRev, humanRev , contaminantsrev)
length(all_d)/2
stopifnot(length(all_d)/2 == length(ecoli) + length(human) + length(msqc1) + length(contNoMSQC1))
writeFasta(all_d, file="../data/fastaFiles/output/p1755_db1_d_20151016_msqc1ecolihuman.fasta")

all <- c(msqc1, ecoli, human, contNoMSQC1)
stopifnot(length(all) == length(ecoli) + length(human) + length(msqc1) + length(contNoMSQC1))

writeFasta(all, file="../data/fastaFiles/output/p1755_db1_20151016_msqc1ecolihuman.fasta")
write.fasta(contaminantsrev, names(contaminantsrev), file='test.fasta',as.string=TRUE, nbchar = 60 )


```

# Site (not more than 4)
VE - Velos
QE - Q-exactive
HF - HF
FU - Fusion
QT - q Trap

# + optional sequential instrument number + 


VE1 - Velos
VIB_200151129_1_VE
<institute>_<date>_<seqnumber>_<instrument>


VIB - Gent
FGCZ - Zurich
IMP - Vienna
CRG - Barcelona
MPI - Dresden




